name: FakeBungee
version: @version@
main: space.mori.fakebungee.FakeBungee
api-version: 1.20
depend:
  - ProtocolLib
  - WorldEdit
  - kotlin-stdlib
softdepend:
  - citizens
authors:
  - dalbodeule
  - ranolp
commands:
  ping:
    usage: "Usage: /<command>"
    permission: fb.ping
  fregion:
    usage: "Usage: /<command>"
    permission: fb.fregion
  fresource:
    usage: "Usage: /<command>"
    permission: fb.fresource
  fconfig:
    usage: "Usage: /<command>"
    permission: fb.fconfig
  fheader:
    usage: "Usage: /<command>"
    permission: fb.fheader
  ffooter:
    usage: "Usage: /<command>"
    permission: fb.ffooter
  resource:
    usage: "Usage: /<command>"
    permission: fb.resource

permissions:
  fb.ping:
    description: Allows ping command
    default: true
  fb.fregion:
    description: Allows region command
    default: op
  fb.fresource:
    description: Allows resource command
    default: op
  fb.fheader:
    description: Allows header command
    default: op
  fb.ffooter:
    description: Allows footer command
    default: op
  fb.resource:
    description: Allows resource command
    default: true
