name: FakeBungee
version: @version@
main: space.mori.fakebungee.FakeBungee
depend: [kotlinbukkit, ProtocolLib, WorldEdit]
authors: [small_sunshine, ranolp]

commands:
  ping:
    usage: "Usage: /<command>"
    permission: fb.ping
  fregion:
    usage: "Usage: /<command>"
    permission: fb.region
  fresource:
    usage: "Usage: /<command>"
    permission: fb.resource
  fconfig:
    usage: "Usage: /<command>"
    permission: fb.config

permissions:
  fb.ping:
    description: Allows ping command
    default: true
  fb.region:
    description: Allows region command
    default: op
  fb.resource:
    description: Allows resource command
    default: op
